
# 服务名
spring:
  application:
    name: xiliu-lease-tenant

  # druid数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置MySQL的驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址(以MySql为例)
    url: jdbc:mysql://localhost:3306/xiliu-lease-tenant?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    # 数据库对应的用户名
    username: root
    # 数据库对应的密码
    password: root
    druid:
      # 配置监控统计拦截的filters，stat是sql监控，wall是防火墙(如果不添加则监控无效)，添加log4j需要引入jar包
      filters: stat,wall,config
      # 连接池最大活跃连接数
      max-active: 100
      # 连接池初始化连接数量
      initial-size: 1
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 连接池最小空闲数
      min-idle: 1
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
      time-between-eviction-runs-millis: 60000
      # 指定一个空闲连接最少空闲多久后可被清除
      min-evictable-idle-time-millis: 300000
      # 连接是否有效的查询语句
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true #\u662F\u5426\u542F\u7528StatFilter\u9ED8\u8BA4\u503Ctrue
        # 排除一些不必要的url，比如.js,/jslib/等
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # 过滤规则
        url-pattern: /*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        # 手动重置监控数据
        enabled: true
        # IP白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP黑名单，若白名单也存在，则优先使用
        deny:
        # 配置druid登录用户名、密码
        login-username: admin
        login-password: admin
        # HTML 中 Reset All 按钮
        reset-enable: true
  redis:
      host: localhost # Redis服务器地址
      database: 10 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      timeout: 3000ms # 连接超时时间（毫秒）

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
  # 逻辑删除
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1
      logic-not-delete-value: 0
  # xml文件路径，classpath* 代表所有模块的resources目录 classpath 不加星号代表当前模块下的resources目录
  mapper-locations: classpath*:mapper/**/*.xml

# 全局日志级别
logging:
  level:
    root: info

jwt:
  tokenHeader: X-Token #JWT存储的请求头
  tokenHead: Bearer  #JWT负载中拿到开头
  secret: yz-admin-secret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间秒(60*60*24)

# xl自定义配置
xl:
  login:
    authcode:
      # 登录验证码是否开启，开发环境配置false方便测试
      enable: false
# 腾讯云cos配置
cos:
  baseUrl: https://xiliu-XXX.cos.ap-guangzhou.myqcloud.com
  secretId: xxxxxxxxx
  secretKey: xxxxxxxx
  regionName: ap-guangzhou
  bucketName: xiliu-XXX
  folderPrefix: /upload